### ISSUE TITLE
Antonio's page

### ISSUE THREAD

**Issue by Pandapo206** [gitdgr1/group_project#1]
Sprint 1 Plan content and style
- [x] moved team information about me into antonio.html #16
- [x] Removed unnecessary comments  #28
Sprint 2
- [x] add a picture to antonios page #59 
- [x] add a return to page link #36 
- [x] add a bio #37 
Sprint 3 
- [x] Add education subpage #67 
- [x] Fixed typos #91 
Sprint 4
- [x] Added more to my bio #92 
- [x] Added my goals in 2nd page #93 
Sprint 5
- [x] Edit Page one #112 
- [x] Add Contact info #113 
- [x] Fixed punctuation on both pages #114
