### ISSUE TITLE
Chris's Page

### ISSUE THREAD

**Issue by NimbusDesign** [gitdgr1/group_project#2]
Sprint 1
- [x] Changed Chris.html to include Chris's info. #17 
- [x] Removed un needed comments #27 

Sprint 2
- [x] Add Image to Page #44
- [x] Change Font #45
- [x] Add Personal Info #46
- [x] Add Return To Main Option to Chris's Page #57

Sprint 3
- [x] Add Education Sub-Page #66

Sprint 4
- [x] Add Bio/Employment Sub-Page #94
