### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by gitdgr1** [gitdgr1/group_project#3]
Create content and decide on styling of main page:
Initial Commit to main branch:
- [x] Create team page
- [x] Create member pages - with instructions in comments

Sprint 1:

- [x] Update color of each team member's name on Main page #14 

Sprint2:
- [x] Enlarge font for team names #55 

Sprint 3:
- [x] Create a new visual style for Team Page
- [x] Bug Fix: Chris' image isn't displaying in new visual style for Team Page #87 
- [x] Bug Fix: Button to move to individual pages only works when clicking on text, not rest of button #88 

Sprint 4:
- [ ] Update summary text for Dinesh #100
