### ISSUE TITLE
Dinesh's Page

### ISSUE THREAD

**Issue by gitdgr1** [gitdgr1/group_project#4]
Initial Commit:
- [x] Create content and define styling for my page

Sprint 1:
- [x] Add link back to the Main Page #39 

Sprint 2:
- [x] Create list of topics and link to topic pages #50 
- [x] For each topic page, add an under construction picture #51 
- [x] Add links to team member pages #52 
- [x] Add Previous and Next navigation between sub-pages #53 

Sprint 3: 
Replace "Under Construction" image on each sub-page with content. For details see Backlog item: Dinesh Subpages. A summary description is available in a new Issue called "Subpages" created by gitdgr1 in repo gitdgr1/group_project. There will be no pull requests associated with this descriptive entry on Sprint 3.

**Comment by gitdgr1** [comment]
Work on this item was completed as part of the initial commit to main
