### ISSUE TITLE
johanna's page

### ISSUE THREAD

**Issue by Johanna206** [gitdgr1/group_project#5]
Sprint 1: 
plan content and style for my page 
- [x]  create content #22
- [x]  create title #23 
- [x] choose styles #24 
- [x] remove unnecessary comments #26

Sprint 2:
- [x] add return to main link #42 
- [x] add a pretty picture #41 
- [x] add link to my other course's page #47 

Sprint 3:
- [x] adjust colors #70 
- [x] add a couple more links #71
