### ISSUE TITLE
Dinesh Subpages

### ISSUE THREAD

**Issue by gitdgr1** [gitdgr1/group_project#73]
Sprint 3:
- [x] Write basic notes about IT 115 learnings #74 
- [x] Add pointer to the group_project Wiki #75 
- [x] Add a few cool pictures to the images directory #76 
- [x] Create list of 3-5 topics with brief descriptions about things I'm trying to learn or would like to learn soon #77 
- [x] Share a few map images and link to xyzmaps #78 
- [x] Fix display bug in Cool Pictures page #80 

Sprint 4:
- [ ] Try out GitHub Actions #99
